FROM almalinux
#CMD [ "ping","-c5","google.com" ]
# ENTRYPOINT [ "ping","-c5","google.com" ]

# Output
# ping -c5 google.com ping -c3 facebook.com

# The best practice is:
CMD [ "google.com" ]
ENTRYPOINT [ "ping", "-c5" ]